services:
  main-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: communet-api
    depends_on:
      - postgres
      - redis
    ports: 
      - "${API_PORT}:${API_PORT}"
    command: "uvicorn --factory main:create_app --reload --host 0.0.0.0 --port ${API_PORT}"
    env_file:
      - .env
    volumes:
      - ./:/app/

  adminer:
    image: adminer
    container_name: communet-adminer
    restart: always
    env_file:
      - .env
    depends_on:
      - postgres
    environment:
      - ADMINER_DESIGN=dracula
    ports:
      - ${ADMINER_PORT}:8080

  postgres:
    image: postgres:latest
    container_name: communet-postgres
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: communet-redis
    restart: always
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - ./redis-data:/data

networks:
  postgres-data:
  redis-data:
