services:
  main-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    ports: 
      - "${API_PORT}:${API_PORT}"
    command: "uvicorn --factory main:create_app --reload --host 0.0.0.0 --port ${API_PORT}"
    env_file:
      - .env
    volumes:
      - ./:/app/
