"""empty message

Revision ID: b1f1b7a43f0d
Revises: 67d52936ff53
Create Date: 2025-02-02 17:31:22.275238

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1f1b7a43f0d'
down_revision: Union[str, None] = '67d52936ff53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chanels', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chanels', 'is_deleted')
    # ### end Alembic commands ###
