"""empty message

Revision ID: e6f2151ee343
Revises: b1f1b7a43f0d
Create Date: 2025-02-02 18:18:51.860257

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6f2151ee343'
down_revision: Union[str, None] = 'b1f1b7a43f0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chanels', 'description',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('chanels', 'avatar',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chanels', 'avatar',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('chanels', 'description',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
